In [1]:
import requests
import time
from mal_scraper import get_user_anime_list
import logging
import pandas as pd
import numpy as np

In [2]:
logging.getLogger('jikanpy').setLevel(logging.CRITICAL)
logging.getLogger().setLevel(logging.CRITICAL)

In [3]:
delay = 1
maxUserSize = 500

In [4]:
def getRandomUser():
    time.sleep(delay)
    url = "https://api.jikan.moe/v4/random/users"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            return data['data']
        elif response.status_code == 429:
            print("Rate limited! Waiting before retry...")
            time.sleep(0.1)
            return getRandomUser()
        else:
            print(f"Error: {response.status_code}")
            return None
            
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

In [5]:
username = "Exarfate"
print(username)

Exarfate

In [6]:
def getReviewsFromUser(username):
    anime_list = get_user_anime_list(username)
    if anime_list is None: return []
    anime_list = [anime for anime in anime_list if anime['score'] > 0]
    return anime_list

In [7]:
anime_list = getReviewsFromUser(username)
print(anime_list)
print(len(anime_list))

[{'name': 'Code Geass: Hangyaku no Lelouch', 'id_ref': 1575, 'consumption_status': <ConsumptionStatus.completed: 'COMPLETED'>, 'is_rewatch': False, 'score': 10, 'progress': 25, 'start_date': None, 'finished_date': None}, {'name': 'Code Geass: Hangyaku no Lelouch R2', 'id_ref': 2904, 'consumption_status': <ConsumptionStatus.completed: 'COMPLETED'>, 'is_rewatch': False, 'score': 10, 'progress': 25, 'start_date': None, 'finished_date': None}]
2

In [8]:
url = "https://api.jikan.moe/v4/top/anime"
popular_anime_ids = []
for page in range(1, 100):
    params = {
        "filter": "bypopularity",
        "page": page,
    }
    response = requests.get(url, params=params)
    time.sleep(delay)
    data = response.json()
    # print(data)
    animes = data['data']
    popular_anime_ids += [anime['mal_id'] for anime in animes]

print(popular_anime_ids)
print(len(popular_anime_ids))

[16498, 1535, 5114, 30276, 38000, 31964, 11757, 11061, 20, 22319, 40748, 32281, 25777, 9253, 1735, 33486, 21, 35760, 28851, 38524, 19815, 1575, 31240, 23273, 36456, 4224, 32182, 20507, 31043, 40028, 22199, 24833, 23755, 269, 6547, 20583, 37779, 30831, 10620, 21881, 1, 9919, 22535, 199, 30, 33352, 44511, 37450, 38691, 2904, 37999, 28223, 38408, 34572, 27899, 50265, 34134, 14719, 18679, 6702, 37521, 35849, 11111, 40456, 3588, 2001, 35790, 28999, 29803, 13601, 28171, 47778, 37510, 9989, 15809, 32937, 28121, 37430, 42897, 34933, 226, 8074, 10087, 39535, 30654, 14813, 28891, 121, 48583, 30503, 31478, 34599, 38671, 11617, 2167, 40591, 6746, 5081, 431, 12189, 14741, 35507, 26243, 52991, 9756, 42249, 51009, 164, 37520, 20899, 41587, 205, 7054, 33206, 32935, 19, 813, 13759, 48736, 6880, 11771, 36511, 4181, 23283, 39587, 10793, 35120, 4898, 31933, 48561, 33255, 26055, 18897, 18153, 37349, 853, 34577, 32282, 40852, 11741, 17265, 22297, 14227, 37991, 523, 23847, 918, 20785, 36474, 30015, 223, 17895, 52299, 50602, 35073, 38826, 5680, 14513, 45576, 15583, 36098, 39551, 51019, 889, 43608, 35968, 30240, 40839, 22043, 6045, 40221, 42203, 38101, 38883, 42310, 52034, 32615, 32, 35788, 30296, 27775, 777, 35062, 1689, 21995, 48926, 37675, 16592, 2025, 356, 41353, 39617, 23289, 41025, 37799, 10165, 849, 49926, 33487, 41457, 15451, 20787, 57334, 36649, 2251, 39195, 30484, 47, 32995, 32867, 46569, 33674, 38680, 24439, 25013, 16782, 34566, 16894, 40776, 28701, 245, 40956, 30694, 41487, 14345, 457, 37347, 37105, 40496, 25157, 32729, 339, 18115, 227, 49596, 11887, 42361, 28907, 38040, 11843, 28623, 10408, 29786, 2966, 1195, 12355, 40356, 4654, 51535, 48316, 249, 50172, 934, 28927, 10719, 28677, 49387, 24703, 18507, 39597, 37086, 2236, 41389, 1210, 54492, 6, 43299, 24415, 32542, 37982, 33506, 13125, 437, 39547, 38329, 49918, 36882, 36896, 39783, 32951, 31859, 14467, 30307, 51096, 31798, 18671, 37210, 39701, 52211, 32998, 270, 47917, 34902, 31765, 877, 11597, 58567, 36949, 31722, 50346, 55701, 32901, 578, 33, 40834, 7791, 51179, 392, 40052, 11759, 27787, 28825, 30123, 35994, 32949, 31646, 28297, 1482, 23233, 2993, 14713, 37987, 52588, 11633, 1818, 34612, 8769, 17074, 790, 23277, 22789, 2476, 33489, 38003, 30544, 34542, 34618, 43, 41467, 22147, 16742, 34280, 37141, 1887, 38659, 14289, 23281, 263, 28977, 40540, 39534, 19163, 3455, 527, 40454, 54112, 225, 53887, 9041, 47194, 36475, 28497, 40938, 39940, 18277, 16870, 6347, 8525, 512, 11499, 36407, 7674, 17729, 8841, 2890, 2034, 7311, 6213, 136, 23321, 7724, 40750, 11577, 48569, 35860, 38668, 16067, 3457, 39533, 47790, 48895, 9513, 39565, 42923, 53393, 35203, 45613, 48580, 14075, 25183, 31580, 2759, 31339, 15315, 38656, 9969, 48661, 1943, 39247, 46095, 8425, 31637, 48549, 7593, 38790, 6707, 31404, 34403, 5630, 34822, 50709, 6594, 3784, 14749, 25397, 15689, 4081, 1604, 40902, 31442, 40417, 52701, 9260, 1519, 27631, 48556, 55888, 120, 4382, 39196, 25781, 42938, 7088, 35972, 14967, 355, 34497, 43523, 34382, 34281, 50631, 48483, 9656, 36296, 35839, 32105, 5681, 49458, 53126, 36563, 8861, 60543, 34561, 34798, 39463, 41084, 22729, 513, 36862, 39017, 37171, 37976, 54595, 34881, 51180, 71, 1840, 40787, 41226, 46352, 11013, 14833, 48413, 10162, 45, 10110, 40357, 5341, 1889, 8675, 35557, 59978, 31741, 55791, 25537, 16011, 59, 32093, 23199, 34662, 31758, 36038, 27989, 31181, 38555, 46102, 55813, 52305, 37984, 40911, 5958, 18397, 40010, 38483, 50594, 23673, 58939, 54744, 54857, 58514, 28755, 41168, 10800, 40935, 7785, 35851, 32899, 50273, 37345, 3785, 41433, 32887, 31636, 31757, 59062, 232, 8937, 33731, 24765, 39741, 44074, 34443, 38186, 41491, 57658, 54789, 34451, 53580, 43692, 42963, 323, 1691, 10863, 41120, 15225, 25835, 15051, 25681, 3712, 36946, 24405, 41623, 31737, 53065, 10161, 16417, 57555, 54900, 40507, 237, 52347, 268, 41710, 54856, 40571, 21603, 13161, 36028, 13659, 28805, 6956, 17549, 31953, 2593, 21855, 44203, 5530, 25159, 34934, 12445, 40586, 59845, 35466, 11319, 8795, 12549, 33502, 28025, 32380, 22145, 50739, 33988, 40530, 4214, 52578, 22265, 185, 22135, 41899, 21843, 35180, 33049, 36633, 35247, 29095, 52807, 4063, 6033, 30363, 39026, 50425, 30749, 6573, 481, 50608, 21647, 55644, 49220, 40046, 32686, 552, 6675, 66, 19221, 6114, 3786, 467, 43969, 41456, 40908, 11981, 27831, 33475, 44961, 20541, 38472, 12531, 18247, 37475, 530, 20031, 572, 16049, 12293, 53998, 47160, 46471, 5, 1292, 11433, 8676, 7817, 10080, 47164, 10490, 15037, 34626, 33050, 585, 48417, 21405, 20853, 40060, 27833, 35838, 30727, 31338, 150, 28249, 41094, 12413, 32379, 32262, 40497, 10790, 38992, 13663, 8630, 7711, 49520, 33926, 24455, 3002, 44942, 20057, 51958, 52830, 31173, 44037, 38397, 50612, 16662, 8516, 228, 22877, 3470, 154, 4752, 19369, 384, 38759, 37786, 51552, 41488, 50461, 40904, 32189, 43690, 13667, 52198, 48849, 35222, 41619, 42351, 235, 57, 38753, 11785, 48760, 7647, 17513, 36793, 16762, 41402, 26349, 857, 10030, 39468, 37095, 38572, 32827, 59192, 39792, 11285, 21085, 35413, 55825, 2246, 58059, 16706, 37744, 2605, 15379, 37497, 34636, 59177, 820, 16524, 30016, 38993, 39326, 50330, 15417, 21431, 5682, 12467, 486, 51367, 9617, 50175, 28725, 48761, 53411, 11703, 2418, 9181, 10495, 40716, 202, 37435, 40595, 6500, 5042, 38080, 33028, 27991, 27821, 34096, 31658, 861, 12365, 31764, 9289, 52741, 31772, 430, 34279, 2104, 40262, 1726, 10396, 55866, 39198, 24, 49114, 30911, 31704, 34437, 17247, 32828, 50416, 9367, 59027, 48415, 22101, 10163, 12291, 35639, 48675, 49709, 49470, 20767, 170, 51213, 36106, 51105, 49891, 34984, 53446, 387, 54865, 20021, 37517, 37965, 22663, 14131, 21557, 50197, 41380, 39710, 47159, 21327, 1698, 49889, 32648, 57524, 4901, 759, 36286, 50380, 57181, 37055, 54714, 24133, 34240, 36726, 41345, 40056, 21939, 31952, 14199, 5258, 36470, 18677, 40004, 39576, 14349, 35847, 49613, 27655, 1559, 10213, 9515, 38414, 8086, 9379, 12477, 40594, 28819, 442, 4059, 2787, 10721, 48548, 9936, 2472, 35946, 39575, 39292, 31845, 33743, 20689, 12859, 51818, 34944, 28735, 6211, 60489, 15039, 16918, 33253, 38084, 101, 31163, 11933, 72, 35076, 15085, 38573, 55690, 31229, 12729, 29758, 53273, 13655, 6811, 597, 8407, 6205, 57592, 38778, 35848, 41006, 39523, 60098, 35608, 1686, 39586, 49930, 56009, 35712, 38610, 3731, 32902, 19647, 25099, 4975, 44524, 47161, 30346, 39491, 35928, 56784, 51064, 58913, 29785, 50307, 53111, 14829, 43007, 79, 28675, 24701, 52215, 51462, 44, 52865, 21863, 38816, 34104, 21339, 43325, 1530, 52635, 44200, 18753, 41461, 34176, 34012, 32188, 26, 7769, 7592, 10521, 4437, 416, 31376, 31374, 4722, 53613, 42192, 42916, 11737, 16, 528, 41930, 41468, 210, 38297, 42205, 47257, 68, 43439, 9062, 21877, 51297, 19429, 189, 41946, 329, 31, 6512, 10588, 8246, 48414, 4155, 51417, 36023, 21105, 28979, 11761, 58426, 20047, 44276, 48643, 6351, 50932, 35376, 10589, 50796, 42282, 38830, 41514, 16001, 33161, 73, 25283, 49438, 36432, 31251, 19111, 23317, 54918, 10379, 30885, 20847, 30458, 34914, 32268, 50392, 239, 2924, 7338, 40620, 48585, 550, 3092, 48753, 41109, 37569, 36027, 5300, 16904, 18689, 5060, 12175, 18245, 38481, 39175, 11665, 2889, 19769, 53516, 3503, 8129, 36266, 40421, 25879, 186, 38793, 58572, 15335, 43609, 16664, 49776, 51122, 12031, 322, 52173, 30736, 41103, 38594, 51498, 29093, 54898, 38480, 60058, 53439, 33836, 31988, 5040, 42340, 49052, 39988, 18139, 37208, 3782, 5277, 40815, 51815, 8460, 145, 936, 4282, 41312, 31245, 38474, 6324, 4725, 4835, 47163, 50593, 14397, 36999, 14353, 36220, 42962, 10067, 56923, 1281, 31490, 16934, 60285, 35737, 40708, 10568, 40542, 53888, 13535, 38249, 40397, 16201, 49784, 21273, 56038, 21561, 34712, 440, 49877, 18179, 10218, 55818, 5356, 6773, 12115, 53447, 20159, 6682, 8424, 31414, 543, 19775, 22687, 31904, 50549, 6747, 42826, 28617, 6922, 41694, 37451, 40333, 54234, 6201, 14837, 52046, 3783, 1571, 34321, 58125, 58390, 801, 1222, 177, 46985, 39324, 21033, 5231, 4280, 29854, 43814, 39555, 4565, 37989, 9863, 9941, 40174, 36838, 60, 52367, 7148, 44055, 35484, 2026, 33047, 51693, 18119, 1827, 35330, 35363, 52093, 4896, 56352, 8247, 31297, 2581, 482, 37614, 7193, 38349, 1313, 12113, 2923, 30187, 433, 33478, 37348, 16009, 52990, 37202, 35079, 9760, 12049, 40729, 9926, 51553, 52736, 34498, 54362, 57892, 35249, 10029, 59160, 42544, 50410, 2129, 52608, 30205, 50854, 52742, 54968, 2144, 21511, 31812, 37491, 32438, 2994, 51648, 16035, 35240, 25731, 3702, 24655, 41812, 33421, 6325, 21507, 53421, 4186, 13367, 4087, 23309, 61322, 40436, 35843, 53632, 53050, 5525, 38234, 13357, 17641, 12967, 31716, 11979, 317, 24231, 40615, 37972, 64, 49979, 31405, 5205, 13271, 34019, 357, 40483, 267, 52955, 37993, 57066, 57058, 51711, 22777, 39030, 4999, 11977, 5781, 37393, 31629, 8142, 18, 48553, 59459, 8557, 37403, 10271, 23623, 6166, 37446, 35459, 50360, 34825, 38145, 49721, 57433, 16353, 874, 39790, 21659, 10711, 10012, 1033, 12431, 19685, 52969, 42625, 53434, 12403, 34055, 29067, 19703, 52481, 37956, 13331, 35905, 15227, 39539, 33286, 31553, 59597, 48418, 49612, 54913, 54837, 48997, 187, 5909, 34964, 32360, 10321, 30778, 3652, 18095, 32983, 34591, 570, 49909, 11179, 36885, 54724, 61316, 1254, 32962, 32979, 54722, 50710, 32900, 5204, 1564, 134, 1117, 376, 67, 36124, 49818, 38889, 1690, 53129, 52995, 42627, 33095, 10357, 13469, 3342, 49233, 22961, 19315, 40059, 25389, 174, 36548, 11701, 10020, 27, 42603, 53770, 19951, 50306, 32370, 38787, 38909, 36754, 42940, 30347, 61469, 36864, 56285, 59986, 9135, 22, 52308, 5940, 44516, 10460, 37396, 42429, 3167, 34103, 15, 36904, 35262, 10155, 60732, 19291, 55265, 24991, 15605, 48, 33929, 32526, 36704, 8888, 52193, 8277, 23251, 12679, 2926, 4107, 59205, 1699, 240, 53730, 61, 15699, 33581, 16732, 50220, 47162, 11553, 22865, 1118, 52816, 17909, 44807, 5030, 33433, 32801, 10456, 38924, 36903, 51098, 32013, 18229, 52446, 195, 4814, 51678, 50582, 1639, 48239, 97, 44204, 44069, 40974, 44881, 469, 1723, 56690, 59229, 13599, 52505, 33071, 3901, 49828, 10079, 5667, 28387, 721, 93, 51705, 30709, 54870, 38328, 885, 54790, 45653, 10578, 53889, 48842, 39486, 59452, 28621, 17777, 33654, 48707, 2963, 36049, 330, 52619, 32603, 3667, 14811, 46093, 23327, 60146, 856, 36516, 138, 31559, 6007, 60371, 31174, 39071, 59708, 11235, 3701, 16668, 169, 51403, 36653, 9330, 59193, 44931, 34620, 1536, 3958, 4981, 33337, 7059, 19489, 30300, 50481, 48633, 38256, 50184, 6372, 57907, 477, 26443, 25015, 901, 468, 182, 5678, 7472, 11123, 23421, 6895, 59970, 37597, 12883, 18195, 40730, 48471, 257, 53200, 34480, 20457, 39063, 23333, 20509, 57616, 40907, 54852, 33003, 51632, 18001, 21353, 31710, 34383, 37806, 8408, 29974, 60593, 24227, 6802, 16512, 3655, 9074, 10049, 153, 15059, 49785, 9982, 23079, 6862, 45055, 395, 39456, 846, 740, 1562, 36873, 1594, 58502, 49413, 90, 43470, 33834, 4789, 400, 34213, 34086, 61026, 32485, 5355, 15565, 51128, 905, 37525, 50, 24705, 32407, 6421, 59145, 49618, 4548, 58172, 687, 13333, 35241, 55830, 22507, 1132, 51252, 40960, 287, 21185, 33094, 35889, 24873, 37259, 38959, 25519, 1119, 59846, 53879, 1029, 33191, 59135, 31592, 256, 52973, 37515, 898, 20709, 26441, 36817, 16005, 1565, 40746, 58359, 35677, 29589, 52657, 2596, 37514, 10397, 27829, 53865, 34494, 3927, 32681, 1829, 33051, 34051, 241, 53802, 17741, 160, 1462, 55848, 617, 10798, 10278, 42590, 2164, 16157, 40623, 532, 24151, 8915, 12893, 48614, 14751, 17831, 51764, 50713, 53835, 51706, 22273, 4744, 25429, 40515, 264, 37379, 139, 18893, 63, 5177, 23777, 34102, 34262, 53488, 32215, 28391, 3572, 459, 3091, 60083, 9736, 855, 30385, 19363, 31680, 114, 534, 4106, 3972, 56964, 27525, 369, 60022, 21563, 52709, 14527, 20973, 34300, 11241, 21329, 50613, 53833, 49980, 36936, 4177, 32245, 57876, 56701, 4472, 6637, 32494, 54703, 666, 16528, 50803, 23311, 80, 25, 57100, 35756, 39570, 58811, 32271, 30230, 48171, 743, 24277, 34544, 56230, 896, 31821, 17389, 39199, 19285, 57891, 147, 19151, 135, 36316, 15687, 13807, 48406, 18857, 58714, 28405, 53263, 18661, 55129, 6030, 31630, 27601, 28285, 35828, 157, 38735, 55997, 36699, 40870, 26351, 34136, 52092, 49894, 22097, 149, 4182, 48903, 30370, 51837, 15119, 32491, 7590, 906, 10073, 11837, 50664, 15197, 903, 17827, 23775, 39705, 36632, 25303, 27633, 54743, 45572, 37926, 2404, 40128, 949, 32673, 37033, 54265, 15117, 62001, 34414, 42072, 53379, 967, 37426, 11266, 9331, 32696, 52196, 38699, 49109, 40532, 57810, 37447, 3297, 42670, 29787, 39607, 53590, 34537, 33012, 30485, 27891, 28957, 33010, 49154, 50275, 44940, 899, 31098, 39569, 57611, 20431, 49782, 10033, 3228, 11743, 3467, 59989, 56062, 55597, 38409, 7662, 23385, 31706, 40392, 59095, 36906, 39808, 9790, 54853, 13851, 10418, 24997, 29317, 35338, 1430, 166, 36652, 9366, 52934, 2952, 21743, 10209, 37823, 24031, 9750, 19365, 32924, 250, 5507, 8426, 56894, 31537, 137, 16397, 51265, 29976, 53407, 10119, 29027, 55102, 38619, 59361, 34392, 28833, 14753, 762, 33513, 56228, 25517, 57025, 9734, 33203, 900, 904, 40936, 42250, 894, 14669, 985, 2216, 54103, 32948, 41392, 54449, 33354, 38935, 902, 9136, 22835, 4551, 36214, 54839, 40682, 5690, 30279, 41265, 5941, 37920, 41911, 18497, 34034, 40685, 59144, 897, 37449, 4581, 4720, 37007, 8476, 14407, 58271, 7465, 45560, 9471, 11079, 33018, 49310, 18617, 6954, 53438, 4477, 18393, 31327, 51212, 51495, 37932, 1239, 50339, 488, 37722, 35821, 10897, 7, 1120, 20931, 46431, 59457, 123, 165, 11751, 49834, 132, 51219, 31914, 56876, 40359, 5112, 25649, 38940, 32668, 10794, 265, 6444, 62568, 62568, 5079, 50205, 4884, 36317, 9479, 37985, 59131, 33036, 50738, 48488, 53040, 58853, 198, 1526, 37981, 243, 28619, 51916, 22547, 14807, 479, 12029, 12231, 24893, 61128, 30383, 49303, 34350, 935, 3229, 39469, 2847, 36039, 37377, 32365, 31389, 3230, 29755, 1142, 834, 37440, 54275, 6987, 58822, 34973, 1088, 1122, 272, 50590, 59983, 372, 2154, 48542, 55742, 42847, 895, 390, 60303, 251, 37986, 59130, 53149, 969, 50404, 30127, 55887, 6793, 15199, 996, 288, 36792, 16890, 50528, 133, 53127, 98, 405, 464, 14765, 8536, 34126, 49605, 8934, 24211, 33377, 1030, 49778, 40269, 248, 59349, 15751, 32936, 37492, 58131, 51020, 15613, 18441, 2961, 51381, 31588, 39355, 522, 379, 55994, 40679, 4192, 28069, 2156, 25687, 27957, 14027, 451, 2002, 13939, 49835, 35983, 39651, 12565, 31109, 2403, 36043, 30901, 52482, 40453, 38450, 12461, 52461, 1606, 14921, 48896, 30806, 32698, 40416, 122, 31051, 710, 13055, 12711, 54632, 16355, 19383, 32086, 53, 94, 51318, 37585, 7627, 54794, 6171, 15911, 48804, 986, 36616, 21681, 30091, 62516, 62516, 2131, 462, 4970, 37579, 325, 32083, 33985, 15109, 8479, 338, 9107, 43756, 32977, 7858, 658, 30014, 59730, 19021, 34438, 6127, 6377, 56538, 33948, 33263, 44406, 51680, 9981, 37719, 2402, 55358, 23209, 34152, 37078, 49469, 10681, 16916, 32981, 13391, 10805, 50652, 460, 30364, 1412, 31500, 51533, 15201, 49981, 32032, 47158, 450, 40858, 65, 15437, 24687, 76, 57584, 10447, 56063, 55071, 52611, 4719, 38843, 55855, 16866, 34541, 42941, 35078, 26165, 37442, 40752, 11783, 452, 55454, 6974, 3087, 59068, 31318, 37441, 732, 53199, 1722, 35110, 5262, 48779, 42395, 59207, 51215, 7058, 31715, 35145, 11077, 55911, 627, 3713, 5150, 1566, 567, 1498, 28883, 38192, 59644, 15377, 6336, 102, 32595, 31931, 54617, 1589, 37716, 12979, 54565, 16774, 61006, 6164, 32071, 74, 35015, 246, 55150, 35434, 2159, 37994, 39799, 30206, 38476, 10378, 1121, 31433, 371, 59267, 48453, 33573, 48492, 35111, 5342, 48702, 34100, 587, 551, 31711, 57217, 53494, 50586, 529, 28, 32607, 9776, 19117, 1965, 5962, 957, 54431, 37407, 32553, 58516, 3974, 34440, 35842, 38085, 58788, 41783, 32323, 15771, 167, 54199, 14293, 36688, 35806, 6574, 57719, 33091, 37021, 40351, 50869, 53410, 21177, 57864, 13411, 25161, 1004, 60326, 2494, 24627, 10298, 49053, 52082, 193, 12815, 24075, 6774, 5039, 1546, 41833, 22433, 1860, 56845, 974, 38731, 61903, 36510, 5118, 2685, 1579, 47250, 49858, 5365, 31326, 12471, 30321, 1050, 59002, 53924, 46422, 7588, 11021, 3299, 34525, 30782, 1250, 58505, 59636, 9834, 4026, 30714, 49357, 30415, 59561, 5671, 32094, 60140, 34161, 37522, 449, 48375, 1293, 59873, 12783, 40215, 42091, 58600, 26213, 52962, 31430, 59711, 3420, 306, 14175, 18295, 30711, 8768, 35503, 2397, 21845, 40784, 30895, 39894, 57380, 53148, 15775, 54233, 33605, 5764, 584, 39388, 20449, 487, 31771, 21437, 21473, 40434, 33417, 52359, 461, 9587, 875, 51794, 17505, 34428, 6178, 57944, 27663, 54915, 207, 37979, 58080, 594, 37621, 40485, 57648, 49722, 40550, 31147, 45486, 51458, 8876, 13403, 10611, 55717, 55973, 859, 196, 53213, 2201, 25867, 21797, 38475, 11739]
2475

In [9]:
def get_anime_reviews_jikan(anime_id, page):
    """
    Get reviews for an anime using Jikan API
    """
    url = f"https://api.jikan.moe/v4/anime/{anime_id}/reviews"
    params = {
        "page": page,
    }
    
    response = requests.get(url, params=params)
    time.sleep(delay)
    
    if response.status_code == 200:
        return response.json()
    else:
        return None

In [10]:
number = 1
t0 = time.time()
distinctUsers = set()
to_graph = [0]
for animeId in popular_anime_ids:
    page = 1
    while len(distinctUsers) < maxUserSize:
    # for page in range(1, 10):        
        data = get_anime_reviews_jikan(animeId, page)
        # print(data)
        for elem in data['data']:
            # print(elem)
            for i, review in enumerate(data['data'], 1):
                # print(f"\nReview {i}:")
                # print(f"User: {review['user']['username']}")
                # print(f"Score: {review['score']}")
                distinctUsers.add(review['user']['username'])

        if not data['pagination']['has_next_page']:
            print(f"{number} ended at: {page} with total of {len(distinctUsers)} users after {time.time() - t0} seconds")
            break
        page += 1
    to_graph.append(len(distinctUsers))
    number += 1

In [11]:
usernames = list(distinctUsers)

In [12]:
rows = []
rowsAtLeast5 = []
usernamesAtLeast5 = []
for username in usernames:
    animeList = getReviewsFromUser(username)
    shortedAnimeList = [{
            'id_ref': entry['id_ref'],
            'name': entry['name'],
            'score': entry['score'],
        } 
        for entry in animeList]
    # print(animeList)
    # print(shortedAnimeList)
    # print(len(animeList))
    rows.append(shortedAnimeList)
    if len(shortedAnimeList) > 4:
        rowsAtLeast5.append(shortedAnimeList)
        usernamesAtLeast5.append(username)

In [13]:
with open("usernames.txt", "w") as f:
    for item in distinctUsers:
        f.write(f"{item}\n")

In [14]:
df = pd.DataFrame([
    {f"{item['id_ref']}_{item['name']}": item['score'] for item in userAnime}
    for userAnime in rows
], index=usernames)

df = df.fillna(0)

df

,1_Cowboy Bebop,47_Akira,6746_Durarara!!,10087_Fate/Zero,11741_Fate/Zero 2nd Season,5114_Fullmetal Alchemist: Brotherhood,270_Hellsing,431_Howl no Ugoku Shiro,11061_Hunter x Hunter (2011),14719_JoJo no Kimyou na Bouken (TV),...,59711_Shibou Yuugi de Meshi wo Kuu.,59459_Silent Witch: Chinmoku no Majo no Kakushigoto,54900_Wind Breaker,56009_Yuusha-kei ni Shosu: Choubatsu Yuusha 9004-tai Keimu Kiroku,3269_.hack//G.U. Trilogy,2823_Barbapapa,3446_Biohazard: Degeneration,10917_Pokemon: Pikachu no Fuyuyasumi (2001),5316_Rape! Rape! Rape!,966_Crayon Shin-chan
Bravo_Zulu,10.0,9.0,8.0,9.0,9.0,10.0,9.0,8.0,10.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
shadovvvvalker,10.0,0.0,0.0,9.0,9.0,8.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Beastm0de23,8.0,8.0,0.0,8.0,8.0,10.0,0.0,8.0,9.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Korukasu,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
deathtousall173,9.0,0.0,8.0,0.0,0.0,9.0,0.0,6.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SaintSinner_,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
themegamancave,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Skittles04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
anarrowstrail,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Anthony_DiGrande,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
df2 = pd.DataFrame([
    {f"{item['id_ref']}_{item['name']}": item['score'] for item in userAnime}
    for userAnime in rowsAtLeast5
], index=usernamesAtLeast5)

df2 = df2.fillna(0)

df2

,1_Cowboy Bebop,47_Akira,6746_Durarara!!,10087_Fate/Zero,11741_Fate/Zero 2nd Season,5114_Fullmetal Alchemist: Brotherhood,270_Hellsing,431_Howl no Ugoku Shiro,11061_Hunter x Hunter (2011),14719_JoJo no Kimyou na Bouken (TV),...,59711_Shibou Yuugi de Meshi wo Kuu.,59459_Silent Witch: Chinmoku no Majo no Kakushigoto,54900_Wind Breaker,56009_Yuusha-kei ni Shosu: Choubatsu Yuusha 9004-tai Keimu Kiroku,3269_.hack//G.U. Trilogy,2823_Barbapapa,3446_Biohazard: Degeneration,10917_Pokemon: Pikachu no Fuyuyasumi (2001),5316_Rape! Rape! Rape!,966_Crayon Shin-chan
Bravo_Zulu,10.0,9.0,8.0,9.0,9.0,10.0,9.0,8.0,10.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
shadovvvvalker,10.0,0.0,0.0,9.0,9.0,8.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Beastm0de23,8.0,8.0,0.0,8.0,8.0,10.0,0.0,8.0,9.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Korukasu,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
deathtousall173,9.0,0.0,8.0,0.0,0.0,9.0,0.0,6.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yhyhyhkt,10.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AnimeCrew,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Katanadude,10.0,0.0,0.0,8.0,9.0,9.0,6.0,0.0,1.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ghier,0.0,7.0,7.0,9.0,9.0,8.0,0.0,7.0,8.0,0.0,...,5.0,5.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
MrLief,9.0,8.0,8.0,9.0,10.0,8.0,6.0,8.0,10.0,9.0,...,0.0,0.0,0.0,0.0,5.0,10.0,1.0,5.0,1.0,6.0

In [16]:
df.to_csv('anime_df.csv')  # index=False removes row numbers
df

,1_Cowboy Bebop,47_Akira,6746_Durarara!!,10087_Fate/Zero,11741_Fate/Zero 2nd Season,5114_Fullmetal Alchemist: Brotherhood,270_Hellsing,431_Howl no Ugoku Shiro,11061_Hunter x Hunter (2011),14719_JoJo no Kimyou na Bouken (TV),...,59711_Shibou Yuugi de Meshi wo Kuu.,59459_Silent Witch: Chinmoku no Majo no Kakushigoto,54900_Wind Breaker,56009_Yuusha-kei ni Shosu: Choubatsu Yuusha 9004-tai Keimu Kiroku,3269_.hack//G.U. Trilogy,2823_Barbapapa,3446_Biohazard: Degeneration,10917_Pokemon: Pikachu no Fuyuyasumi (2001),5316_Rape! Rape! Rape!,966_Crayon Shin-chan
Bravo_Zulu,10.0,9.0,8.0,9.0,9.0,10.0,9.0,8.0,10.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
shadovvvvalker,10.0,0.0,0.0,9.0,9.0,8.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Beastm0de23,8.0,8.0,0.0,8.0,8.0,10.0,0.0,8.0,9.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Korukasu,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
deathtousall173,9.0,0.0,8.0,0.0,0.0,9.0,0.0,6.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SaintSinner_,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
themegamancave,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Skittles04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
anarrowstrail,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Anthony_DiGrande,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
print(len(usernames))

500