In [1]:
import requests
import time
from mal_scraper import get_user_anime_list
import logging
import pandas as pd
import numpy as np
import os

In [2]:
logging.getLogger('jikanpy').setLevel(logging.CRITICAL)
logging.getLogger().setLevel(logging.CRITICAL)

In [3]:
delay = 1
maxUserSize = 2000

In [4]:
def getRandomUser():
    time.sleep(delay)
    url = "https://api.jikan.moe/v4/random/users"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            return data['data']
        elif response.status_code == 429:
            print("Rate limited! Waiting before retry...")
            time.sleep(0.1)
            return getRandomUser()
        else:
            print(f"Error: {response.status_code}")
            return None
            
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

In [5]:
username = "Exarfate"
print(username)

Exarfate

In [17]:
def getReviewsFromUser(username):
    anime_list = get_user_anime_list(username)
    time.sleep(delay)
    if anime_list is None: return []
    anime_list = [anime for anime in anime_list if anime['score'] > 0]
    return anime_list

In [7]:
anime_list = getReviewsFromUser(username)
print(anime_list)
print(len(anime_list))

[{'name': 'Code Geass: Hangyaku no Lelouch', 'id_ref': 1575, 'consumption_status': <ConsumptionStatus.completed: 'COMPLETED'>, 'is_rewatch': False, 'score': 10, 'progress': 25, 'start_date': None, 'finished_date': None}, {'name': 'Code Geass: Hangyaku no Lelouch R2', 'id_ref': 2904, 'consumption_status': <ConsumptionStatus.completed: 'COMPLETED'>, 'is_rewatch': False, 'score': 10, 'progress': 25, 'start_date': None, 'finished_date': None}]
2

In [8]:
url = "https://api.jikan.moe/v4/top/anime"
while True:
    response = requests.get(url)
    
    time.sleep(delay)
    
    data = response.json()
    if not 'status' in data or data['status'] != 500:
        break

In [9]:
url = "https://api.jikan.moe/v4/top/anime"
popular_anime_ids = []
for page in range(1, 20):
    params = {
        "filter": "bypopularity",
        "page": page,
    }
    response = requests.get(url, params=params)
    time.sleep(delay)
    data = response.json()
    # print(data)
    animes = data['data']
    popular_anime_ids += [anime['mal_id'] for anime in animes]

print(popular_anime_ids)
print(len(popular_anime_ids))

[16498, 1535, 5114, 30276, 38000, 31964, 11757, 11061, 20, 22319, 40748, 32281, 25777, 9253, 1735, 33486, 21, 35760, 28851, 38524, 19815, 1575, 31240, 23273, 36456, 4224, 32182, 20507, 31043, 40028, 22199, 24833, 23755, 269, 6547, 20583, 37779, 30831, 10620, 21881, 1, 9919, 22535, 30, 199, 33352, 44511, 37450, 38691, 2904, 37999, 28223, 38408, 34572, 27899, 50265, 34134, 14719, 18679, 6702, 37521, 35849, 11111, 40456, 3588, 2001, 35790, 28999, 29803, 13601, 28171, 47778, 37510, 9989, 15809, 32937, 28121, 37430, 42897, 34933, 226, 8074, 10087, 39535, 30654, 14813, 28891, 48583, 121, 30503, 31478, 34599, 38671, 11617, 2167, 40591, 5081, 6746, 431, 12189, 35507, 14741, 26243, 52991, 9756, 42249, 51009, 164, 37520, 20899, 41587, 205, 7054, 19, 33206, 32935, 48736, 813, 13759, 6880, 11771, 36511, 4181, 39587, 23283, 10793, 35120, 4898, 31933, 48561, 33255, 26055, 18897, 18153, 37349, 853, 34577, 32282, 40852, 11741, 17265, 22297, 37991, 14227, 523, 23847, 918, 20785, 36474, 52299, 30015, 223, 17895, 50602, 35073, 38826, 5680, 45576, 14513, 36098, 15583, 51019, 39551, 43608, 889, 35968, 30240, 40839, 22043, 42203, 6045, 38101, 40221, 42310, 38883, 52034, 32615, 32, 35788, 30296, 27775, 777, 35062, 1689, 21995, 48926, 37675, 16592, 2025, 356, 41353, 39617, 41025, 23289, 37799, 10165, 849, 49926, 57334, 33487, 41457, 15451, 20787, 36649, 39195, 2251, 46569, 30484, 47, 32867, 32995, 33674, 38680, 24439, 25013, 16782, 34566, 16894, 40776, 28701, 245, 40956, 30694, 41487, 14345, 37105, 457, 37347, 40496, 25157, 339, 32729, 18115, 49596, 227, 11887, 42361, 38040, 28907, 11843, 28623, 29786, 10408, 2966, 1195, 48316, 12355, 40356, 51535, 4654, 50172, 249, 934, 49387, 28927, 28677, 10719, 24703, 39597, 18507, 54492, 37086, 41389, 2236, 1210, 6, 43299, 24415, 32542, 37982, 49918, 437, 38329, 39547, 33506, 13125, 36882, 39783, 36896, 32951, 31859, 51096, 14467, 30307, 31798, 18671, 37210, 52211, 39701, 47917, 32998, 270, 34902, 58567, 877, 31765, 55701, 50346, 11597, 36949, 31722, 578, 33, 32901, 51179, 40834, 7791, 392, 40052, 11759, 27787, 28825, 30123, 35994, 32949, 31646, 28297, 52588, 1482, 23233, 37987, 14713, 2993, 11633, 1818, 34612, 17074, 8769, 790, 23277, 22789, 2476, 33489, 38003, 41467, 30544, 43, 34542, 34618, 22147, 16742, 34280, 37141, 38659, 1887, 14289, 263, 23281, 28977, 40540, 39534, 19163, 3455, 54112, 527, 53887, 40454, 47194, 225, 9041, 36475, 28497, 40938, 39940, 18277, 16870, 6347, 512, 8525, 11499, 36407, 7674, 17729, 8841, 2890, 2034, 7311, 136, 6213, 7724, 23321, 40750, 48569, 11577, 38668, 35860, 47790, 16067, 39533, 3457, 48895, 39565, 42923, 9513, 53393, 45613, 48580, 35203, 14075, 25183, 31580, 2759, 31339, 15315, 48661, 38656, 9969, 1943, 39247, 46095, 48549, 31637, 8425, 38790, 7593, 6707, 31404, 34403, 34822, 5630, 50709, 3784, 6594, 14749, 25397, 15689, 4081, 40902, 1604, 52701, 31442, 40417, 9260, 1519, 55888, 27631, 48556, 4382, 39196, 120, 25781, 42938, 7088, 43523, 35972, 14967, 34497, 355, 34281, 50631, 34382, 48483, 9656, 36296, 60543, 35839, 32105, 49458, 53126, 5681, 36563, 8861, 34561, 34798, 39463, 41084, 59978, 36862, 22729, 513, 54595, 51180, 39017, 37171, 37976]
475

In [10]:
def get_anime_reviews_jikan(anime_id, page):
    """
    Get reviews for an anime using Jikan API
    """
    url = f"https://api.jikan.moe/v4/anime/{anime_id}/reviews?page={page}"
    #params = {"page": page,}
    print(url)
    
    response = requests.get(url)
    time.sleep(delay)
    
    if response.status_code == 200:
        return response.json()
    else:
        return None

In [11]:
number = 1
t0 = time.time()
distinctUsers = set()
start = 0

In [12]:
from pathlib import Path

while True:
    file_path = Path(f"aaa_{start}")
    if not file_path.exists():
        break
        
    with open(file_path, 'r') as f:
        for line in f:
            user = line.strip()
            if user:
                distinctUsers.add(user)
    
    start += 1

print(f"Found {len(distinctUsers)} unique users.")

Found 0 unique users.

In [13]:
for ind in range(start, len(popular_anime_ids)):
    animeId = popular_anime_ids[ind]
    print(animeId)
    page = 1
    while True:
        print()
    # for page in range(1, 10):        
        data = get_anime_reviews_jikan(animeId, page)
        # print("AAA", page, data)
        print(data)

        if not data or ('status' in data and data['status'] == 500):
            page += 1
            continue

        number_of_failed_attempts = 0
            
        for elem in data['data']:
            for i, review in enumerate(data['data'], 1):
                # print(f"\nReview {i}:")
                # print(f"User: {review['user']['username']}")
                # print(f"Score: {review['score']}")
                distinctUsers.add(review['user']['username'])

        if not data['pagination']['has_next_page']:
            print(f"{number} ended at: {page} with total of {len(distinctUsers)} users after {time.time() - t0} seconds")
            break
        page += 1
    number += 1
    if len(distinctUsers) >= maxUserSize:
        print(f"Ending with {len(distinctUsers)}")
        break

start = ind

16498

https://api.jikan.moe/v4/anime/16498/reviews?page=1

In [14]:
print(len(distinctUsers))

2147

In [15]:
usernames = list(distinctUsers)

In [16]:
rows = []
rowsAtLeast5 = []
usernamesAtLeast5 = []
for username in usernames:
    animeList = getReviewsFromUser(username)
    shortedAnimeList = [{
            'id_ref': entry['id_ref'],
            'name': entry['name'],
            'score': entry['score'],
        } 
        for entry in animeList]
    # print(animeList)
    # print(shortedAnimeList)
    # print(len(animeList))
    rows.append(shortedAnimeList)
    if len(shortedAnimeList) > 4:
        rowsAtLeast5.append(shortedAnimeList)
        usernamesAtLeast5.append(username)

c:\Users\mateu\AppData\Local\Python\pythoncore-3.13-64\Lib\site-packages\mal_scraper\users.py:341: SyntaxWarning: invalid escape sequence '\/'
  "video_url":"\/anime\/32998\/91_Days\/video",

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Istniejące połączenie zostało gwałtownie zamknięte przez zdalnego hosta', None, 10054, None))

In [ ]:
with open("usernames.txt", "w") as f:
    for item in distinctUsers:
        f.write(f"{item}\n")

In [ ]:
df = pd.DataFrame([
    {f"{item['id_ref']}_{item['name']}": item['score'] for item in userAnime}
    for userAnime in rows
], index=usernames)

df = df.fillna(0)

df

,32998_91 Days,11759_Accel World,31580_Ajin,6547_Angel Beats!,9989_Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.,24833_Ansatsu Kyoushitsu,30654_Ansatsu Kyoushitsu 2nd Season,34443_Baki,288_Bakuten Shoot Beyblade,37498_Black Fox,...,10507_Inazuma Eleven Go,9032_Inazuma Eleven: Saikyou Gundan Ogre Shuurai,50325_Kaguya-sama wa Kokurasetai: Ultra Romantic Teaser PV - Ishigami Yuu wa Kataritai,39651_Mob Psycho 100: Dai Ikkai Rei toka Soudansho Ian Ryokou - Kokoro Mitasu Iyashi no Tabi,36616_Mob Psycho 100: Reigen - Shirarezaru Kiseki no Reinouryokusha,57864_Monogatari Series: Off & Monster Season,40489_Sword Art Online: Alicization - War of Underworld Reflection,36539_Tsuki ga Kirei Special,13261_Inazuma Eleven Go: Chrono Stone,33733_Inazuma Eleven: Ares no Tenbin
ItIsIDio,6.0,6.0,8.0,5.0,2.0,8.0,8.0,5.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Rhapsody-,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
JonerBaloner,0.0,0.0,0.0,8.0,9.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CHZabuza,6.0,5.0,0.0,0.0,0.0,7.0,7.0,9.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Butterflight,0.0,0.0,0.0,9.0,9.0,7.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
vasolina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Shirogari,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tyrannicswine117,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PoltergeistChan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Profane_Vestige,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df2 = pd.DataFrame([
    {f"{item['id_ref']}_{item['name']}": item['score'] for item in userAnime}
    for userAnime in rowsAtLeast5
], index=usernamesAtLeast5)

df2 = df2.fillna(0)

df2

,32998_91 Days,11759_Accel World,31580_Ajin,6547_Angel Beats!,9989_Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.,24833_Ansatsu Kyoushitsu,30654_Ansatsu Kyoushitsu 2nd Season,34443_Baki,288_Bakuten Shoot Beyblade,37498_Black Fox,...,10507_Inazuma Eleven Go,9032_Inazuma Eleven: Saikyou Gundan Ogre Shuurai,50325_Kaguya-sama wa Kokurasetai: Ultra Romantic Teaser PV - Ishigami Yuu wa Kataritai,39651_Mob Psycho 100: Dai Ikkai Rei toka Soudansho Ian Ryokou - Kokoro Mitasu Iyashi no Tabi,36616_Mob Psycho 100: Reigen - Shirarezaru Kiseki no Reinouryokusha,57864_Monogatari Series: Off & Monster Season,40489_Sword Art Online: Alicization - War of Underworld Reflection,36539_Tsuki ga Kirei Special,13261_Inazuma Eleven Go: Chrono Stone,33733_Inazuma Eleven: Ares no Tenbin
ItIsIDio,6.0,6.0,8.0,5.0,2.0,8.0,8.0,5.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Rhapsody-,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
JonerBaloner,0.0,0.0,0.0,8.0,9.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CHZabuza,6.0,5.0,0.0,0.0,0.0,7.0,7.0,9.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Butterflight,0.0,0.0,0.0,9.0,9.0,7.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PyraXadon,0.0,0.0,1.0,6.0,6.0,8.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Honksea,7.0,0.0,0.0,10.0,8.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Fueeru,0.0,5.0,6.0,8.0,9.0,8.0,10.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GregRocks,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BetterTaste,7.0,6.0,8.0,6.0,7.0,5.0,0.0,0.0,0.0,0.0,...,6.0,6.0,8.0,6.0,7.0,8.0,3.0,6.0,2.0,4.0

In [ ]:
df.to_csv('anime_df.csv')  # index=False removes row numbers

In [ ]:
df_ind = 1
while True:
    filename = f"anime_df_{df_ind}.csv"
    
    if not os.path.exists(filename):
        break
            
    df_ind += 1

In [ ]:
df.to_csv(f"anime_df_{df_ind}.csv")

In [ ]:
print(len(usernames))

678

In [ ]:
print(start)